### ISSUE TITLE
Add support to merge duplicate oas paths using disputePrefix

### ISSUE THREAD

**Issue by robertmassaioli** [robertmassaioli/openapi-merge#8]
Moved from: https://bitbucket.org/echo_rm/openapi-merge/issues/4/add-support-to-merge-duplicate-oas-paths

![Screen Shot 2021-09-04 at 2 48 49 pm](https://user-images.githubusercontent.com/149178/132082815-da03624e-f648-4254-8be9-3f47c0291e94.png)

![Screen Shot 2021-09-04 at 2 49 00 pm](https://user-images.githubusercontent.com/149178/132082819-b5cab2c5-f093-4ae9-90a1-37a3a8e213c0.png)

While trying to use your library we ran into an issue where our library has a preset amount of paths and a client application that can override them. Because we also use express-openapi-validator we need a cleanly merged OAS file between the two. I’ve created a fix and associated tests but am unable to open a pull request. You can find my proposed solution here: https://bitbucket.org/drethic/openapi-merge/src/oas-path-dispute-prefix/.

Thank you for your consideration in fixing this issue.

[edit-1]

Note: If the newer path only adds/overrides an operation it will replace the whole path. I’ll think on a cleaner solution but in the short term this should get one step closer to seamless merging of two files with identical paths.

**Comment by Drethic** [comment]
@robertmassaioli Thank you for keeping this issue alive.  Did you want me to move the proposed solution code from bitbucket to here?

**Comment by robertmassaioli** [comment]
If you could that would be convenient, thankyou. I'm re-evaluating all of these issues when time allows. Cheers.

**Comment by macux** [comment]
I'm looking for something similar here - I have a need to merge a command and a query service into a single swagger file. So for example the command side might have a path "/users" with a POST and the query side would have the same path "/users" with a GET. Any idea if the above would resolve this and if the PR will go through any time soon?

Thanks!

**Comment by Drethic** [comment]
I have been meaning to migrate the code I pushed to Bitbucket but due to work priorities I have not been able to get it ported and updated per the threads above.  The original branch is [here](https://bitbucket.org/drethic/openapi-merge/src/oas-path-dispute-prefix/) if you or @robertmassaioli want to pull it over, clean it up, and see about getting it merged.  For me I've just used it locally as that project requires.

**Comment by malaclypse** [comment]
Would this cover the case where you have one spec with a get operation and another with a post, under the same path? Any plans to add this functionality?

**Comment by dbryar** [comment]
https://github.com/robertmassaioli/openapi-merge/pull/78 resolves this to some degree

**Comment by robertmassaioli** [comment]
Following up after re-evaluating the open issues here — this is partially resolved, with one part of the original ask still outstanding.

The scenario in the screenshots above — two inputs each contributing *different* HTTP methods to the same path (e.g. `GET /users` from one service, `POST /users` from another) — is now handled by a `duplicatePathHandling: 'merge-operations'` option on each input, added for #71:

```jsonc
{
  "inputs": [
    { "inputFile": "./service-a.yaml", "duplicatePathHandling": "merge-operations" },
    { "inputFile": "./service-b.yaml", "duplicatePathHandling": "merge-operations" }
  ],
  "output": "./merged.yaml"
}
```

When the method sets are disjoint and the path-level fields (`parameters`, `summary`, `servers`, etc.) agree, the two path items are combined into one. It refuses (with a clear `duplicate-paths` error) whenever combining would be a guess — overlapping methods, differing path-level fields, or either side being a `$ref`.

**What's still open:** the original ask here was specifically to apply the `dispute` prefix/suffix to disambiguate two inputs that define the *same* method on the *same* path — genuine overlap, not just two different methods sharing a path. `merge-operations` deliberately does not attempt that; it errors out rather than guessing which definition should win or how to rename one. That part of this issue hasn't been implemented.

**Note on timing:** `merge-operations` has been merged to `main` and ships in the next npm release (`1.4.0`) — not yet on the currently published `1.3.3` / `1.3.2`.

I'm closing this since the scenario in the original report (and the one most people watching this issue have needed, per the comments) is now covered. If you specifically need the same-method-same-path dispute-prefix behaviour, please open a new issue describing that case directly — it's a narrower, still-unsolved problem and deserves its own tracking rather than staying buried in this one.

Details: `ai-planning/issues/11-proposal-71-skip-duplicate-paths.md` (see §10.5 for exactly this gap).
